### ISSUE TITLE
Change args to [-B] to force make

### ISSUE THREAD

**Issue by Freed-Wu** [gnagel/pre-commit-python#2]
make will work when the time stamp of source is older than the target. However, pre-commit-hook will change time stamp. Such as
```
---
repos:
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.5.1
    hooks:
      - id: markdownlint-cli2
        additional_dependencies:
          - markdown-it-texmath@0.9.1
  - repo: https://github.com/gnagel/pre-commit-make
    rev: main
    hooks:
      - id: make
        args:
          README.md
```

markdownlint always update markdown's time stamp, which make `make README.md` cannot work. So `-B` is needed. Thanks.
